### ISSUE TITLE
isoAnnotate error

### ISSUE THREAD

**Issue by zxl124** [lpantano/isomiRs#18]
Thank you so much for this useful package.

When running `isoAnnotate` I encountered the following error:
```
Error in `[[<-.data.frame`(`*tmp*`, "edit_mature_position", value = c("NA",  : 
  replacement has 3762 rows, data has 3504
```
[The input](https://github.com/lpantano/isomiRs/files/5066373/mirtop_rawData.tsv.zip) was generated using `mirtop export`, then loaded into isomiRs using `IsomirDataSeqFromMirtop`. Other isomiRs functions seemed to work correctly. Not sure if this error originated from `mirtop` or `isomiRs`.

`isomiRs` version 1.16.2 was installed using Bioconductor on R 4.0.2.

Thanks in advance for looking into this.

**Comment by lpantano** [comment]
Sorry I missed this, there was an issues with my github notification and I missed a bunch. Happy to help if still needed.

**Comment by lpantano** [comment]
Do you think you can share the R object for me to take a look? And what version of R are you using? Thanks

**Comment by bounlu** [comment]
Unfortunately I am not able to share the R object but I think it is a reproducible error as other users also experienced it. I am using `R 4.3.2`.

**Comment by karlaarz** [comment]
Hello, I was wondering if you were able to solve this? I get the same error:
```
Error in `[[<-.data.frame`(`*tmp*`, "edit_mature_position", value = c("NA",  : 
  replacement has 966 rows, data has 887
```

I'm using R.4.2.0

**Comment by lpantano** [comment]
Hi, I couldn't find the error, do you think you can find some data to share? it would be much easier to find the problem. I could be some small dataset, maybe only a couple of samples or anonymized the samples names. Happy to help if I have something to work with.

Thanks

**Comment by lpantano** [comment]
you can use the email in my GitHub profile. thanks!

**Comment by lpantano** [comment]
I pushed a change, if you could install from the main branch to try again.

But I think the issue is from mirtop as mention here: https://github.com/miRTop/mirtop/issues/80

I think I need to try to reproduce that error.  Any change I can get the data from the mirtop export step? Maybe only having WT1 and WT2 samples are enough.

**Comment by lpantano** [comment]
just pinging here, in case you can share those files.thanks

**Comment by karlaarz** [comment]
Hi Lorena, sorry for my late reply. I had the chance to run the pipeline again using the latest version of R (4.4.1), and the latest installation from the main branch that you suggested, and now I don't get the error anymore. Maybe the error was because my previous version of R was 4.1? Thanks for the help!

**Comment by lpantano** [comment]
it could be, but I pushed a fixed to main branch and to the dev in bioconductor so maybe that helped as well.
